[build]
  publish = "public"
  command = ""

# See https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects
[[redirects]]
  from = "https://zacharybetz.com/*"
  to = "https://zwbetz.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.zacharybetz.com/*"
  to = "https://www.zwbetz.com/:splat"
  status = 301
  force = true
